[2,"\n"]
[1,"\nStarting python3 kernel..."]
[1,"Done\n"]
[1,"\nExecuting 'model.ipynb'\n  Cell 1/9..."]
[1,"Done\n  Cell 2/9..."]
[1,"ERROR: \n\nAn error occurred while executing the following cell:\n------------------\ncon = duckdb.connect('my-db.duckdb')\ndf = penguins.load_penguins()\ncon.register('df',df)\ncon.execute('CREATE TABLE penguins AS SELECT * FROM df')\ncon.close()\n------------------\n\n\n\u001B[1;31m---------------------------------------------------------------------------\u001B[0m\n\u001B[1;31mCatalogException\u001B[0m                          Traceback (most recent call last)\nCell \u001B[1;32mIn[2], line 4\u001B[0m\n\u001B[0;32m      2\u001B[0m df \u001B[38;5;241m=\u001B[39m penguins\u001B[38;5;241m.\u001B[39mload_penguins()\n\u001B[0;32m      3\u001B[0m con\u001B[38;5;241m.\u001B[39mregister(\u001B[38;5;124m'\u001B[39m\u001B[38;5;124mdf\u001B[39m\u001B[38;5;124m'\u001B[39m,df)\n\u001B[1;32m----> 4\u001B[0m \u001B[43mcon\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mexecute\u001B[49m\u001B[43m(\u001B[49m\u001B[38;5;124;43m'\u001B[39;49m\u001B[38;5;124;43mCREATE TABLE penguins AS SELECT * FROM df\u001B[39;49m\u001B[38;5;124;43m'\u001B[39;49m\u001B[43m)\u001B[49m\n\u001B[0;32m      5\u001B[0m con\u001B[38;5;241m.\u001B[39mclose()\n\n\u001B[1;31mCatalogException\u001B[0m: Catalog Error: Table with name \"penguins\" already exists!\n\n"]
